services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend-NestJS
    container_name: nestjs_backend
    command: npm run start:dev 
    develop:
      watch: 
        - action: sync
          path: ./src
          target: /src/backend
          ignore: 
            - node_modules/
        - action: rebuild
          path: package.json

    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 123
      DATABASE_NAME: postgres
    ports:
      - "3001:3001"
    volumes:
      - ./backend-NestJS:/usr/src/app
    depends_on:
      - postgres

  frontend:
    build: ./frontend-React
    container_name: react_frontend
    command: npm start 
    develop:
      watch: 
        - action: sync
          path: ./src
          target: /src/frontend
          ignore: 
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
