services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend-NestJS
      dockerfile: dockerfile
    container_name: nestjs_backend
    command: npm run start:dev 
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 123
      DATABASE_NAME: postgres
    ports:
      - "3001:3001"
    env_file:
      - .env   
    depends_on:
      - postgres

  frontend:
    build: 
      context: ./frontend-React
      dockerfile: dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
