# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /toro-todo/backend-NestJS

# Copy the package.json and package-lock.json files to the container
COPY package.json .

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the NestJS application
RUN npm run build

# Expose the port the app runs on
EXPOSE 3001

# Run the NestJS application
CMD ["npm", "run", "start:dev"]
